package com.shxy.model;

import java.io.Serializable;
import java.util.Date;

public class Company implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.c_id
     *
     * @mbggenerated
     */
    private Integer cId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.c_name
     *
     * @mbggenerated
     */
    private String cName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.c_creattime
     *
     * @mbggenerated
     */
    private Date cCreattime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.c_type
     *
     * @mbggenerated
     */
    private String cType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.c_rank
     *
     * @mbggenerated
     */
    private String cRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.c_m_type
     *
     * @mbggenerated
     */
    private String cMType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.c_count
     *
     * @mbggenerated
     */
    private String cCount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column company.c_address
     *
     * @mbggenerated
     */
    private String cAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table company
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.c_id
     *
     * @return the value of company.c_id
     *
     * @mbggenerated
     */
    public Integer getcId() {
        return cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.c_id
     *
     * @param cId the value for company.c_id
     *
     * @mbggenerated
     */
    public void setcId(Integer cId) {
        this.cId = cId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.c_name
     *
     * @return the value of company.c_name
     *
     * @mbggenerated
     */
    public String getcName() {
        return cName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.c_name
     *
     * @param cName the value for company.c_name
     *
     * @mbggenerated
     */
    public void setcName(String cName) {
        this.cName = cName == null ? null : cName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.c_creattime
     *
     * @return the value of company.c_creattime
     *
     * @mbggenerated
     */
    public Date getcCreattime() {
        return cCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.c_creattime
     *
     * @param cCreattime the value for company.c_creattime
     *
     * @mbggenerated
     */
    public void setcCreattime(Date cCreattime) {
        this.cCreattime = cCreattime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.c_type
     *
     * @return the value of company.c_type
     *
     * @mbggenerated
     */
    public String getcType() {
        return cType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.c_type
     *
     * @param cType the value for company.c_type
     *
     * @mbggenerated
     */
    public void setcType(String cType) {
        this.cType = cType == null ? null : cType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.c_rank
     *
     * @return the value of company.c_rank
     *
     * @mbggenerated
     */
    public String getcRank() {
        return cRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.c_rank
     *
     * @param cRank the value for company.c_rank
     *
     * @mbggenerated
     */
    public void setcRank(String cRank) {
        this.cRank = cRank == null ? null : cRank.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.c_m_type
     *
     * @return the value of company.c_m_type
     *
     * @mbggenerated
     */
    public String getcMType() {
        return cMType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.c_m_type
     *
     * @param cMType the value for company.c_m_type
     *
     * @mbggenerated
     */
    public void setcMType(String cMType) {
        this.cMType = cMType == null ? null : cMType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.c_count
     *
     * @return the value of company.c_count
     *
     * @mbggenerated
     */
    public String getcCount() {
        return cCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.c_count
     *
     * @param cCount the value for company.c_count
     *
     * @mbggenerated
     */
    public void setcCount(String cCount) {
        this.cCount = cCount == null ? null : cCount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column company.c_address
     *
     * @return the value of company.c_address
     *
     * @mbggenerated
     */
    public String getcAddress() {
        return cAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column company.c_address
     *
     * @param cAddress the value for company.c_address
     *
     * @mbggenerated
     */
    public void setcAddress(String cAddress) {
        this.cAddress = cAddress == null ? null : cAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Company other = (Company) that;
        return (this.getcId() == null ? other.getcId() == null : this.getcId().equals(other.getcId()))
            && (this.getcName() == null ? other.getcName() == null : this.getcName().equals(other.getcName()))
            && (this.getcCreattime() == null ? other.getcCreattime() == null : this.getcCreattime().equals(other.getcCreattime()))
            && (this.getcType() == null ? other.getcType() == null : this.getcType().equals(other.getcType()))
            && (this.getcRank() == null ? other.getcRank() == null : this.getcRank().equals(other.getcRank()))
            && (this.getcMType() == null ? other.getcMType() == null : this.getcMType().equals(other.getcMType()))
            && (this.getcCount() == null ? other.getcCount() == null : this.getcCount().equals(other.getcCount()))
            && (this.getcAddress() == null ? other.getcAddress() == null : this.getcAddress().equals(other.getcAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getcId() == null) ? 0 : getcId().hashCode());
        result = prime * result + ((getcName() == null) ? 0 : getcName().hashCode());
        result = prime * result + ((getcCreattime() == null) ? 0 : getcCreattime().hashCode());
        result = prime * result + ((getcType() == null) ? 0 : getcType().hashCode());
        result = prime * result + ((getcRank() == null) ? 0 : getcRank().hashCode());
        result = prime * result + ((getcMType() == null) ? 0 : getcMType().hashCode());
        result = prime * result + ((getcCount() == null) ? 0 : getcCount().hashCode());
        result = prime * result + ((getcAddress() == null) ? 0 : getcAddress().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table company
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", cId=").append(cId);
        sb.append(", cName=").append(cName);
        sb.append(", cCreattime=").append(cCreattime);
        sb.append(", cType=").append(cType);
        sb.append(", cRank=").append(cRank);
        sb.append(", cMType=").append(cMType);
        sb.append(", cCount=").append(cCount);
        sb.append(", cAddress=").append(cAddress);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}