package com.shxy.model;

import java.io.Serializable;

public class Person implements Serializable {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.p_id
	 *
	 * @mbggenerated
	 */
	private Integer pId;
	
	private int pAgeCount;
	

	public int getpAgeCount() {
		return pAgeCount;
	}

	public void setpAgeCount(int pAgeCount) {
		this.pAgeCount = pAgeCount;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.p_name
	 *
	 * @mbggenerated
	 */
	private String pName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.p_sex
	 *
	 * @mbggenerated
	 */
	private String pSex;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.p_idcard
	 *
	 * @mbggenerated
	 */
	private String pIdcard;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.p_age
	 *
	 * @mbggenerated
	 */
	private Integer pAge;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.p_birth
	 *
	 * @mbggenerated
	 */
	private String pBirth;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.p_address
	 *
	 * @mbggenerated
	 */
	private String pAddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.p_grade
	 *
	 * @mbggenerated
	 */
	private String pGrade;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column person.c_id
	 *
	 * @mbggenerated
	 */
	private Integer cId;

	private String pType;

	public String getpType() {
		return pType;
	}

	public void setpType(String pType) {
		this.pType = pType;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database table person
	 *
	 * @mbggenerated
	 */
	private static final long serialVersionUID = 1L;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.p_id
	 *
	 * @return the value of person.p_id
	 *
	 * @mbggenerated
	 */
	public Integer getpId() {
		return pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.p_id
	 *
	 * @param pId
	 *            the value for person.p_id
	 *
	 * @mbggenerated
	 */
	public void setpId(Integer pId) {
		this.pId = pId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.p_name
	 *
	 * @return the value of person.p_name
	 *
	 * @mbggenerated
	 */
	public String getpName() {
		return pName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.p_name
	 *
	 * @param pName
	 *            the value for person.p_name
	 *
	 * @mbggenerated
	 */
	public void setpName(String pName) {
		this.pName = pName == null ? null : pName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.p_sex
	 *
	 * @return the value of person.p_sex
	 *
	 * @mbggenerated
	 */
	public String getpSex() {
		return pSex;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.p_sex
	 *
	 * @param pSex
	 *            the value for person.p_sex
	 *
	 * @mbggenerated
	 */
	public void setpSex(String pSex) {
		this.pSex = pSex == null ? null : pSex.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.p_idcard
	 *
	 * @return the value of person.p_idcard
	 *
	 * @mbggenerated
	 */
	public String getpIdcard() {
		return pIdcard;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.p_idcard
	 *
	 * @param pIdcard
	 *            the value for person.p_idcard
	 *
	 * @mbggenerated
	 */
	public void setpIdcard(String pIdcard) {
		this.pIdcard = pIdcard == null ? null : pIdcard.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.p_age
	 *
	 * @return the value of person.p_age
	 *
	 * @mbggenerated
	 */
	public Integer getpAge() {
		return pAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.p_age
	 *
	 * @param pAge
	 *            the value for person.p_age
	 *
	 * @mbggenerated
	 */
	public void setpAge(Integer pAge) {
		this.pAge = pAge;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.p_birth
	 *
	 * @return the value of person.p_birth
	 *
	 * @mbggenerated
	 */
	public String getpBirth() {
		return pBirth;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.p_birth
	 *
	 * @param pBirth
	 *            the value for person.p_birth
	 *
	 * @mbggenerated
	 */
	public void setpBirth(String pBirth) {
		this.pBirth = pBirth == null ? null : pBirth.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.p_address
	 *
	 * @return the value of person.p_address
	 *
	 * @mbggenerated
	 */
	public String getpAddress() {
		return pAddress;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.p_address
	 *
	 * @param pAddress
	 *            the value for person.p_address
	 *
	 * @mbggenerated
	 */
	public void setpAddress(String pAddress) {
		this.pAddress = pAddress == null ? null : pAddress.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.p_grade
	 *
	 * @return the value of person.p_grade
	 *
	 * @mbggenerated
	 */
	public String getpGrade() {
		return pGrade;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.p_grade
	 *
	 * @param pGrade
	 *            the value for person.p_grade
	 *
	 * @mbggenerated
	 */
	public void setpGrade(String pGrade) {
		this.pGrade = pGrade == null ? null : pGrade.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column person.c_id
	 *
	 * @return the value of person.c_id
	 *
	 * @mbggenerated
	 */
	public Integer getcId() {
		return cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column person.c_id
	 *
	 * @param cId
	 *            the value for person.c_id
	 *
	 * @mbggenerated
	 */
	public void setcId(Integer cId) {
		this.cId = cId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	@Override
	public boolean equals(Object that) {
		if (this == that) {
			return true;
		}
		if (that == null) {
			return false;
		}
		if (getClass() != that.getClass()) {
			return false;
		}
		Person other = (Person) that;
		return (this.getpId() == null ? other.getpId() == null : this.getpId().equals(other.getpId()))
				&& (this.getpName() == null ? other.getpName() == null : this.getpName().equals(other.getpName()))
				&& (this.getpSex() == null ? other.getpSex() == null : this.getpSex().equals(other.getpSex()))
				&& (this.getpIdcard() == null ? other.getpIdcard() == null
						: this.getpIdcard().equals(other.getpIdcard()))
				&& (this.getpAge() == null ? other.getpAge() == null : this.getpAge().equals(other.getpAge()))
				&& (this.getpBirth() == null ? other.getpBirth() == null : this.getpBirth().equals(other.getpBirth()))
				&& (this.getpAddress() == null ? other.getpAddress() == null
						: this.getpAddress().equals(other.getpAddress()))
				&& (this.getpGrade() == null ? other.getpGrade() == null : this.getpGrade().equals(other.getpGrade()))
				&& (this.getcId() == null ? other.getcId() == null : this.getcId().equals(other.getcId()));
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((getpId() == null) ? 0 : getpId().hashCode());
		result = prime * result + ((getpName() == null) ? 0 : getpName().hashCode());
		result = prime * result + ((getpSex() == null) ? 0 : getpSex().hashCode());
		result = prime * result + ((getpIdcard() == null) ? 0 : getpIdcard().hashCode());
		result = prime * result + ((getpAge() == null) ? 0 : getpAge().hashCode());
		result = prime * result + ((getpBirth() == null) ? 0 : getpBirth().hashCode());
		result = prime * result + ((getpAddress() == null) ? 0 : getpAddress().hashCode());
		result = prime * result + ((getpGrade() == null) ? 0 : getpGrade().hashCode());
		result = prime * result + ((getcId() == null) ? 0 : getcId().hashCode());
		return result;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	@Override
	public String toString() {
		StringBuilder sb = new StringBuilder();
		sb.append(getClass().getSimpleName());
		sb.append(" [");
		sb.append("Hash = ").append(hashCode());
		sb.append(", pId=").append(pId);
		sb.append(", pName=").append(pName);
		sb.append(", pSex=").append(pSex);
		sb.append(", pIdcard=").append(pIdcard);
		sb.append(", pAge=").append(pAge);
		sb.append(", pBirth=").append(pBirth);
		sb.append(", pAddress=").append(pAddress);
		sb.append(", pGrade=").append(pGrade);
		sb.append(", cId=").append(cId);
		sb.append(", serialVersionUID=").append(serialVersionUID);
		sb.append("]");
		return sb.toString();
	}
}