package com.shxy.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.shxy.model.Person;

public interface PersonMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer pId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	int insert(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	int insertSelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	Person selectByPrimaryKey(Integer pId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Person record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table person
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Person record);

	List<Person> listAllPerson();//功能：查询所有人信息    场景：显示数据

	List<Person> listPersonByType(String pType);//功能：根据type查询人员信息    场景：显示数据

	List<Person> selectByNameAndBirth(@Param("pName") String pName, @Param("pBirth") String pBirth);//功能：根据姓名和出生日期查询人员信息    场景：查询信息
	
	List<Map<Integer,Integer>> selectByAgeAndCount();//功能：查询所有年龄以及对应的数量    场景：highchart饼图制作
	
	List<Map<String ,Object>> selectTraineeLimit(Map<Integer,Integer> m);//功能：limit限制查询数量    场景：datagrid分页控件    备注：跟下面的一个方法实现的效果一样
	
	List<Person> selectTraineeLimite(Map<Integer,Integer> m);//功能：limit限制查询数量    场景：datagrid分页控件
	
	long getTraineeTotal();//功能：查询总数人    场景：datagrid分页控件
	
	int addsomeperson(List<Person> list);//功能：根据list批量导入数据        场景：导入excel数据
}