package com.shxy.dao;

import java.util.List;

import com.shxy.model.Ztree;


public interface ZtreeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_tree
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_tree
     *
     * @mbggenerated
     */
    int insert(Ztree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_tree
     *
     * @mbggenerated
     */
    int insertSelective(Ztree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_tree
     *
     * @mbggenerated
     */
    Ztree selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_tree
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Ztree record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table z_tree
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Ztree record);
    
    List<Ztree> selectall();
}